import turtle

t = turtle.Turtle()

t.pencolor("blue")
t.fillcolor("blue")
t.begin_fill()
t.setheading(180)
for i in range(2):
    t.forward(200)
    t.right(90)
    t.forward(100)
    t.right(90)
t.end_fill()
t.penup()
t.pencolor("red")
t.fillcolor("red")
t.forward(30)
t.right(90)
t.pendown()
t.begin_fill()
t.circle(30)
t.end_fill()
t.penup()
t.left(90)
t.forward(80)
t.right(90)
t.pendown()
t.begin_fill()
t.circle(30)
t.end_fill()
turtle.done()